Huge improvement to config-container script - working with arrays instead of strings - fail if immage is defined but empty, starts with special chars,   ends with special chars, ... - better formated ... and more

diff --git a/.local/bin/config-container b/.local/bin/config-container
--- a/.local/bin/config-container
+++ b/.local/bin/config-container
@@ -3,6 +3,14 @@
 # I wanted to learn how to use case/shift, so I wrote this script which
 # makes debugging the dotfiles in different Distros a bit more comfy.
 
+# initialize variables
+DEBUG=false
+workdir=/root
+shell=""
+installcmd=()
+pkgs=()
+
+# read arguments
 for arg in "$@"; do
     case "${arg[@]}" in
         -h | --help)
@@ -34,6 +42,51 @@ for arg in "$@"; do
                 && exit 1
             if [[ "${arg}" != *"="* ]]; then
                 shift
+                [ -z "$1" ] \
+                    && echo "error: image can not be empty" \
+                    && exit 1
+                [ "${1:0:1}" = "-" ] \
+                    && echo "error: image can not start with a dash" \
+                    && exit 1
+                [ "${1:0:1}" = "/" ] \
+                    && echo "error: image can not start with a slash" \
+                    && exit 1
+                [ "${1:0:1}" = ":" ] \
+                    && echo "error: image can not start with a colon" \
+                    && exit 1
+                [ "${1: -1}" = ":" ] \
+                    && echo "error: image can not end with a colon" \
+                    && exit 1
+                [ "${1: -1}" = "/" ] \
+                    && echo "error: image can not end with a slash" \
+                    && exit 1
+                [ "${1: -1}" = "-" ] \
+                    && echo "error: image can not end with a dash" \
+                    && exit 1
+                [ "${1: -1}" = "." ] \
+                    && echo "error: image can not end with a dot" \
+                    && exit 1
+                [ "${1: -1}" = "_" ] \
+                    && echo "error: image can not end with an underscore" \
+                    && exit 1
+                [ "${1: -1}" = "@" ] \
+                    && echo "error: image can not end with an at sign" \
+                    && exit 1
+                [ "${1: -1}" = "!" ] \
+                    && echo "error: image can not end with an exclamation mark" \
+                    && exit 1
+                [ "${1: -1}" = "#" ] \
+                    && echo "error: image can not end with a hash" \
+                    && exit 1
+                [ "${1: -1}" = "$" ] \
+                    && echo "error: image can not end with a dollar sign" \
+                    && exit 1
+                [ "${1: -1}" = "%" ] \
+                    && echo "error: image can not end with a percent sign" \
+                    && exit 1
+                [ "${1: -1}" = "^" ] \
+                    && echo "error: image can not end with a caret" \
+                    && exit 1
                 image="$1"
             else
                 image="${arg#*=}"
@@ -48,7 +101,7 @@ for arg in "$@"; do
             ;;
         *)
             shift
-            [[ -z $arg ]] \
+            [[ "$arg" = "$1" ]] \
                 && printf "error: unknown argument: %s\n" "$arg" \
                 && exit 1
             ;;
@@ -58,30 +111,29 @@ done
 
 # set dotfiles to default if not set
 export dotfiles=${dotfiles:-$HOME/git/mauwii/dotfiles}
-[[ "${DEBUG:-false}" == "true" ]] \
-    && echo "dotfiles set to: ${dotfiles}"
+[[ "${DEBUG}" == true ]] && echo "dotfiles set to: ${dotfiles}"
 
 # set image to default if not set
 export image="${image:-debian:bookworm}"
-[[ "${image}" == "debian:bookworm" && "$no_pkgs" != true && "${DEBUG:-false}" == "true" ]] \
+[[ "${image}" == "debian:bookworm" && "${no_pkgs}" != true && "${DEBUG}" == true ]] \
     && printf "no image set, using default: %s\n" "${image}"
 
 # set shell and installcmd based on image
 case "${image}" in
-    */alpine:* | */alpine | alpine:*)
+    */alpine:* | */alpine | alpine:* | alpine)
         shell="/bin/ash"
-        installcmd="apk add --no-cache"
-        pkgs="bat direnv exa nano pandoc w3m w3m-image"
+        installcmd=("apk" "add" "--no-cache")
+        pkgs=("bat" "direnv" "exa" "nano" "pandoc" "starship" "w3m" "w3m-image")
         ;;
-    */ubuntu:* | */ubuntu | ubuntu:*)
+    */ubuntu:* | */ubuntu | ubuntu:* | ubuntu)
         shell="/bin/bash"
-        installcmd="apt-get update && apt-get install -y --no-install-recommends"
-        pkgs="bat direnv exa nano pandoc w3m w3m-img"
+        installcmd=(apt-get update \&\& apt-get install -y --no-install-recommends)
+        pkgs=(bat direnv exa nano pandoc w3m w3m-img)
         ;;
-    */debian:* | */debian | debian:*)
+    */debian:* | */debian | debian:* | debian)
         shell="/bin/bash"
-        installcmd="apt-get update && apt-get install -y --no-install-recommends"
-        pkgs="bat direnv exa nano pandoc w3m w3m-img"
+        installcmd=(apt-get update \&\& apt-get install -y --no-install-recommends)
+        pkgs=(bat direnv exa nano pandoc w3m w3m-img)
         ;;
     *)
         printf "couldn't detect distro, will try to install %s without packages\n" "${image}"
@@ -89,22 +141,32 @@ case "${image}" in
         ;;
 esac
 
-# unset pkgs if no_pkgs is set
+# unset installcmd and pkgs if no_pkgs is set
 if [ "$no_pkgs" == true ]; then
-    unset pkgs installcmd \
-        && [ "$DEBUG" = "true" ] \
-        && printf "no packages will be installed\n"
+    pkgs=()
+    installcmd=()
+    [ "$DEBUG" = true ] && printf "no packages will be installed\n"
 fi
 
+# set container cmd
+container_cmd=(
+    "${installcmd[@]}" "${pkgs[@]}" ${pkgs:+&&} "${shell}" "dotfiles/.dotfiles/setup_local.sh" ${shell:+&&} "${shell}" "-l"
+)
+[ "${DEBUG}" == true ] && printf "container cmd set to: %s\n" "${container_cmd[*]}"
+
 # print debug message if DEBUG is set
-[[ "${DEBUG:-false}" == "true" && "$no_pkgs" != true && "$no_img" != true ]] \
-    && printf "will use %s with these options:\n\t%s%s%s\n" "${image}" "${shell}" "${installcmd}" "${pkgs}"
+[[ "${DEBUG}" == true && "$no_pkgs" != true && "$no_img" != true ]] \
+    && printf "will use %s with these options:\n\t%s %s %s\n" "${image}" "${shell}" "${installcmd[*]}" "${pkgs[*]}"
 
 # execute container interactive
 docker run \
-    --rm --interactive --tty --workdir=/root \
+    --rm \
+    --interactive \
+    --tty \
+    --workdir="${workdir}" \
     -v "${dotfiles}:/root/dotfiles" \
     -e DEBIAN_FRONTEND=noninteractive \
     -e "DEBUG=$DEBUG" \
     "${image:-debian:bookworm}" \
-    sh -c "${installcmd:+$installcmd $pkgs &&} $shell dotfiles/.dotfiles/setup_local.sh && $shell -l"
+    /bin/sh -c "${container_cmd[*]}"
+# sh -c "${installcmd:+$installcmd $pkgs &&} $shell dotfiles/.dotfiles/setup_local.sh && $shell -l"
